### ISSUE TITLE
New account creation, login, and guest/demo login review

### ISSUE THREAD

**Issue by eric-pinero** [eric-pinero/bootbeginner#2]
- [x] Users can sign up, sign in, log out
- [x] Users can use a demo login to try the site
- [x] Users can't use certain features without logging in (creating or backing projects, liking projects)
- [x] Completely styled and seeded

**Comment by jliversi** [comment]
Really good job overall, mostly just small styling changes necessary. 
- [ ] The buttons on your navBar are currently too spread (and are too close to the edges of the screen). Get them to be in the same places they are on kickstarter.
- [ ] On your sign in page, the spacing on the form is a little bit off (it's more spaced out on your than kickstarter). Same for your sign-up form. It's slight, but let's try to get it pixel-perfect. 
- [ ] For your sign-up form, you should have a email confirmation and password confirmation that appear after focusing on your email and password inputs for the first time. Then you can run a check in handleSubmit to make sure these match the other fields. 
- [ ] On your signup form, your demo login is falling outside of the form. 
- [ ] Your logout button should be part of a dropdown from clicking on a top right icon. 
- [ ] BootBeginner logo should be a link to "/"

**Comment by eric-pinero** [comment]
I'll eventually need to double back to the dropdown and give it the ability to display the user's backed and created projects.

**Comment by jliversi** [comment]
Overall it looks really great right now, just have two super minor changes and then you're user_auth is entirely done:
- [ ] The search icon is a little higher than the Search link, bring down the icon so it's on the same line.
- [ ] Your buttons on your forms should have a pointer cursor, and the colors that you're fading between aren't exactly right.
